### Inputs:
- name: SLM_CLIENT | Assert Inputs | create_resource.yml
  ansible.builtin.assert:
    that:
      - (slm_client_slm_base_url is defined) and (slm_client_slm_base_url | length > 0)
      - (slm_client_user_access_token is defined) and (slm_client_user_access_token | length > 0)
      - (slm_client_resource_id is defined) and (slm_client_resource_id | length > 0)
      - (slm_client_user_id is defined) and (slm_client_user_id | length > 0)
      - (slm_client_credential_id is defined) and (slm_client_credential_id | length > 0)

### Optional Inputs:
# - slm_client_remote_access_service_connection_type (default='ssh') # ssh or rdp
# - slm_client_remote_access_service_connection_port (default=22) # port number for ssh or rdp

- name: Assign RemoteAccessService with Credential to resource
  ansible.builtin.uri:
    url: "{{ slm_client_slm_base_url }}/resource-management/resources/{{ slm_client_resource_id }}/remote-access"
    validate_certs: false
    method: POST
    headers:
      Authorization: "Bearer {{ slm_client_user_access_token }}"
    body_format: json
    body:
      fullPathOwnerGroupId: "/users/{{ slm_client_user_id }}"
      credentialId: "{{ slm_client_credential_id }}"
      connectionType: "{{ slm_client_remote_access_service_connection_type | default('ssh') }}"
      connectionPort: "{{ slm_client_remote_access_service_connection_port | default(22) }}"
