### Inputs:
- name: SLM_CLIENT | Assert Inputs | create_username_password_credential.yml
  ansible.builtin.assert:
    that:
      - (slm_client_slm_base_url is defined) and (slm_client_slm_base_url | length > 0)
      - (slm_client_user_access_token is defined) and (slm_client_user_access_token | length > 0)
      - (slm_client_user_id is defined) and (slm_client_user_id | length > 0)
      - (slm_client_resource_username is defined) and (slm_client_resource_username | length > 0)
      - (slm_client_resource_password is defined) and (slm_client_resource_password | length > 0)

### Outputs:
- name: SLM_CLIENT | Set credential id
  ansible.builtin.set_fact:
    slm_client_credential_id: "{{ (slm_client_resource_username + ':' + slm_client_resource_password) | to_uuid }}"

- name: Create Credential
  ansible.builtin.uri:
    url: "{{ slm_client_slm_base_url }}/platform-management/credentials/{{ slm_client_credential_id }}"
    validate_certs: false
    method: PUT
    headers:
      Authorization: "Bearer {{ slm_client_user_access_token }}"
    body_format: json
    body:
      credential:
        id: "{{ slm_client_credential_id }}"
        name: "{{ slm_client_resource_username }}"
        scopesRaw:
          - REMOTE_ACCESS
        data:
          credentialDataType: USERNAME_PASSWORD
          username: "{{ slm_client_resource_username }}"
          password: "{{ slm_client_resource_password }}"
      entityLinks: []
      fullPathOwnerGroupId: "/users/{{ slm_client_user_id }}"
  register: slm_client_create_credential_response
  failed_when:
    - slm_client_create_credential_response.status not in [200]
    - "'Duplicate entry' not in slm_client_create_credential_response.json.message"
