### Inputs:
- name: SLM_CLIENT | Assert Inputs | create_resource.yml
  ansible.builtin.assert:
    that:
      - (slm_client_slm_base_url is defined) and (slm_client_slm_base_url | length > 0)
      - (slm_client_user_access_token is defined) and (slm_client_user_access_token | length > 0)
      - (slm_client_resource_hostname is defined) and (slm_client_resource_hostname | length > 0)
      - (slm_client_resource_ip_address is defined) and (slm_client_resource_ip_address | length > 0)
      - (slm_client_user_id is defined) and (slm_client_user_id | length > 0)

### Optional Inputs:
# - slm_client_resource_username # otherwise no credential will be created and assigned to the resource
# - slm_client_resource_password # otherwise no credential will be created and assigned to the resource
# - slm_client_remote_access_service_connection_type (default='ssh') # ssh or rdp
# - slm_client_remote_access_service_connection_port (default=22) # port number for ssh or rdp

- name: SLM_CLIENT | Get resources
  ansible.builtin.include_tasks:
    file: "{{ role_path }}/tasks/get_resources.yml"

- name:  SLM_CLIENT | Add Resource via SLM API
  when: slm_client_resource_ip_address not in slm_resource_ips
  ansible.builtin.uri:
    url: "{{ slm_client_slm_base_url }}/resource-management/resources"
    validate_certs: false
    method: POST
    headers:
      Content-Type: "application/json"
      Authorization: "Bearer {{ slm_client_user_access_token }}"
    body_format: json
    body:
      resourceHostname: "{{ slm_client_resource_hostname }}"
      resourceIp: "{{ slm_client_resource_ip_address }}"
      fullPathOwnerGroupId: "/users/{{ slm_client_user_id }}"
    status_code: [200, 500]
  register: slm_client_add_resource_response
  retries: 5
  until: slm_client_add_resource_response.status != 405 # 405 Method Not Allowed is returned when slm is starting
  vars:
    slm_resource_ips: "{{ (slm_client_resources | map(attribute='ip') | list) | default([]) }}"

- name: SLM_CLIENT | Get resource by IP address
  ansible.builtin.include_tasks:
    file: "{{ role_path }}/tasks/get_resource_by_ip.yml"

### Outputs:
- name: SLM_CLIENT | Set resource creation response
  ansible.builtin.set_fact:
    slm_client_resource: "{{ slm_client_resource_by_ip }}"
    slm_client_resource_id: "{{ slm_client_resource_by_ip.id }}"

- name: SLM_CLIENT | Create Username/Password Credential and Assign to Resource
  when:
    - (slm_client_resource_username | default('') | length > 0)
    - (slm_client_resource_password | default('') | length > 0)
  ansible.builtin.include_tasks:
    file: "{{ role_path }}/tasks/{{ task_file }}"
  loop:
    - "create_username_password_credential.yml"
    - "assign_credential_to_resource.yml"
  loop_control:
    loop_var: task_file
